### ISSUE TITLE
Sunrise/Sunset minutes formatting is wrong for values with one digit

### ISSUE THREAD

**Issue by cyrusmg** [calzoneman/i3-weather#14]
**Reproduction step:** use `--format "{sunrise} - {sunset}"`
**Currently displays:** `5:8 am - 8:44 pm`.
**Expected:** `5:08 am - 8:44 pm`

**Comment by calzoneman** [comment]
I believe this is an issue with Yahoo! Weather itself since those attributes are simply being dumped from the XML: https://github.com/calzoneman/i3-weather/blob/master/weather.py#L66-L67

That said, it might be possible to hack around this by using a regex to replace such errors.
